name: 'StackSpot AI Security Action POC '

description: 'StackSpot AI Security Action POC '

inputs:
  CLIENT_ID:
    description: Account client id
    required: true
  CLIENT_KEY:
    description: Account client secret key
    required: true
  CLIENT_REALM:
    description: Account slug
    required: true
  QC_SLUG:
    description: Quick Command slug
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        matrix: true
      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      # with:
      #   since_last_remote_commit: true 
    
    - name: Check changed files
      run: echo ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10' 

    - name: Install python libraries 
      run: pip install requests
      shell: bash

    - name: Run SAST Remote Quick Command
      id: rqc
      env:
        CLIENT_ID: ${{ inputs.CLIENT_ID }}
        CLIENT_KEY: ${{ inputs.CLIENT_KEY }}
        CLIENT_REALM: ${{ inputs.CLIENT_REALM }}
        QC_SLUG: ${{ inputs.QC_SLUG }}
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        if [ ${{runner.os}} != 'Windows' ]; then
          python3 ${{ github.action_path }}/sast-rqc.py
        elif [ ${{runner.os}} == 'Windows' ]; then
          python ${{ github.action_path }}\sast-rqc.py
        else
          echo "${{runner.os}} not supported"
          exit 1
        fi
      shell: bash

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      if: ${{ steps.rqc.outputs.result != '' }}
      with:
        issue-number: ${{ github.event.number }}
        body: |
          Identified security vulnerabilities through `stackspot-ai-security-action-poc` action:
          ```
          ${{ steps.rqc.outputs.result }}
          ```
        reactions: 'eyes'

branding:
    icon: 'terminal'
    color: 'gray-dark'