name: Action Test Ubuntu

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: GuillaumeFalourd/stackspot-ai-security-action-poc@main
        id: run
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_REALM: stackspot
          QC_SLUG: sast-rqc

      - name: Commit and Push new file
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          target_branch: test